name: rockstar_app
description: 이 시대의 밴드맨이라면.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0

  english_words: ^4.0.0
  provider: ^6.0.0
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0 
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/rockstar_logo.png
    - assets/logo/rockstar_icon.png
    - assets/logo/rockstar_text.png
    - assets/logo/crown.png
  fonts:
    - family: PixelFont
      fonts:
        - asset: assets/fonts/DungGeunMo.ttf