// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKPRtOPDG0ZLgaMioFHb5bd3AHEFV1Dfk',
    appId: '1:491163937365:web:627282ac3e0971152782dc',
    messagingSenderId: '491163937365',
    projectId: 'rockstar-f9295',
    authDomain: 'rockstar-f9295.firebaseapp.com',
    storageBucket: 'rockstar-f9295.firebasestorage.app',
    measurementId: 'G-FGX658DE9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnE8kFhNP9osUJSJ1KJUozpaVKgzAyZ6I',
    appId: '1:491163937365:android:d7d77160c13dfb0b2782dc',
    messagingSenderId: '491163937365',
    projectId: 'rockstar-f9295',
    storageBucket: 'rockstar-f9295.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhB7vulbQLgFrlsFB4UUXdFEUbi8tnvNU',
    appId: '1:491163937365:ios:7dc709f130be79c62782dc',
    messagingSenderId: '491163937365',
    projectId: 'rockstar-f9295',
    storageBucket: 'rockstar-f9295.firebasestorage.app',
    iosBundleId: 'com.suzzingv.rockstar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhB7vulbQLgFrlsFB4UUXdFEUbi8tnvNU',
    appId: '1:491163937365:ios:1cb94d58a31dce3c2782dc',
    messagingSenderId: '491163937365',
    projectId: 'rockstar-f9295',
    storageBucket: 'rockstar-f9295.firebasestorage.app',
    iosBundleId: 'com.example.rockstarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKPRtOPDG0ZLgaMioFHb5bd3AHEFV1Dfk',
    appId: '1:491163937365:web:b53600dd075092aa2782dc',
    messagingSenderId: '491163937365',
    projectId: 'rockstar-f9295',
    authDomain: 'rockstar-f9295.firebaseapp.com',
    storageBucket: 'rockstar-f9295.firebasestorage.app',
    measurementId: 'G-BMN00WYCYQ',
  );
}
